# Main compose file for ROS-master with the container from Dockerhub.
version: '2.1'

services:
  lidar:
    image: windesheimwinny/lidar:latest
    networks:
      - ros
    restart: always

networks:
  ros:
